name: TownyPlusPlus
version: '0.10.0'
main: org.polithill.TownyPlusPlus
authors: [Vodomer, Witux]
api-version: '1.17'
commands:
  tsunami:
  towny++:
    description: "Основная команда плагина"
    usage: "/towny++ [reload|info]"
    permission: "townyplusplus.use"
    permission-message: "У вас нет прав на использование этой команды"
  crumblecookie:
    description: "Пример команды"
    usage: "/crumblecookie"